name: editorconfig-checker

on:
  pull_request:
  push:

jobs:
  build:
    name: editorconfig-checker
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v5.0.0
        with:
          persist-credentials: false
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
